
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;
using System.Drawing;
// Create single instance of sample data from first line of dataset for model input
var image = (Bitmap)Image.FromFile(@"D:\presentations\mlnet-modelbuilder-talk\data\flowers\flower_photos\daisy\100080576_f52e8ee070_n.jpg");
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    ImageSource = image,
};
// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");

